import { StyleSheet } from 'react-native';

import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: colors.navy,
    flex: 1,
    overflow: 'hidden',
  },
  scrollContent: {
    flexGrow: 1,
  },
  content: {
    alignSelf: 'center',
    flex: 1,
    maxWidth: 720,
    paddingBottom: 24,
    paddingHorizontal: 22,
    paddingTop: 14,
    width: '100%',
  },
  decorativeCircleTop: {
    backgroundColor: 'rgba(193, 18, 31, 0.18)',
    borderRadius: 170,
    height: 340,
    position: 'absolute',
    right: -185,
    top: -130,
    width: 340,
  },
  decorativeCircleBottom: {
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 145,
    borderWidth: 44,
    bottom: -180,
    height: 290,
    left: -150,
    position: 'absolute',
    width: 290,
  },
  brandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  brandMark: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 13,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  brandMarkText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: -0.3,
  },
  brandName: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1.1,
  },
  brandCaption: {
    color: '#AEB9CC',
    fontSize: 11,
    marginTop: 2,
  },
  hero: {
    marginTop: 48,
  },
  eyebrow: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.09)',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  eyebrowText: {
    color: '#E3E8F1',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.65,
  },
  title: {
    color: '#FFFFFF',
    fontSize: 46,
    fontWeight: '800',
    letterSpacing: -1.6,
    lineHeight: 50,
    marginTop: 20,
  },
  description: {
    color: '#B9C3D5',
    fontSize: 16,
    lineHeight: 24,
    marginTop: 17,
    maxWidth: 580,
  },
  classCard: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 20,
    flexDirection: 'row',
    marginTop: 36,
    padding: 15,
  },
  classBadge: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: 15,
    height: 62,
    justifyContent: 'center',
    width: 62,
  },
  classBadgeValue: {
    color: colors.primary,
    fontSize: 21,
    fontWeight: '900',
    lineHeight: 22,
  },
  classBadgeLabel: {
    color: colors.primary,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.8,
    marginTop: 2,
  },
  classDetails: {
    flex: 1,
    marginLeft: 14,
    minWidth: 0,
  },
  classTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '800',
  },
  classSchedule: {
    color: colors.muted,
    fontSize: 13,
    marginTop: 5,
  },
  liveIndicator: {
    alignItems: 'center',
    backgroundColor: colors.successSoft,
    borderRadius: 999,
    flexDirection: 'row',
    gap: 5,
    marginLeft: 8,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  liveDot: {
    backgroundColor: colors.success,
    borderRadius: 4,
    height: 7,
    width: 7,
  },
  liveText: {
    color: colors.success,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  highlightsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 15,
  },
  highlightItem: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.07)',
    borderColor: 'rgba(255, 255, 255, 0.09)',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 6,
    paddingVertical: 12,
  },
  highlightValue: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
  },
  highlightLabel: {
    color: '#AEB9CC',
    fontSize: 10,
    marginTop: 3,
    textAlign: 'center',
  },
  footer: {
    marginTop: 'auto',
    paddingTop: 32,
  },
  footerText: {
    color: '#8290A8',
    fontSize: 11,
    marginTop: 14,
    textAlign: 'center',
  },
});
